# run: tmuxinator start -p tmuxinator.yml
name: persist-theme

on_project_start: 
  - docker-compose up -d
  - open http://persist.localhost/

windows:
  - watchers:
      - nvm use 14
      - composer install
      - yarn
      - yarn build
      - yarn start
  - editor: $EDITOR
